# =============================================
# PICOM CONFIG — Tiago (Notebook Mint)
# =============================================

# --- Backend ---
backend = "glx";

# --- Bordas arredondadas ---
corner-radius = 12;
rounded-corners-exclude = [
  "class_g = 'Polybar'"
];

# --- Transparência ---
inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 1.0;

# --- Sombras ---
shadow = true;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
shadow-exclude = [
  "class_g = 'Polybar'"
];

# --- Fade ---
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

# --- Misc ---
vsync = true;
mark-wmname-focused = true;
detect-client-opacity = true;
